<<<<<<< HEAD
print("welcome to hexen. what do you want to do?\n")
print("1. quick single card spread")
print("2. daily check-in tarot spread")
print("3. guidance, experiences and lessons daily tarot spread")
print("4. hidden thruths daily tarot spread")





def throw(a):
    from PIL import Image
    import random
    switcher = {
        1: "two of chalices, upright: unity, partnership, connection.",
        2: "three of chalices, upright: friendship, community, happiness.",
        3: "four of chalices, upright: apathy, contemplation, disconnectedness.",
        4: "five of chalices, upright: loss, grief, self-pity.",
        5: "six of chalices, upright: familiarity, happy memories, healing.",
        6: "seven of chalices, upright: searching for purpose, choices, daydreaming.",
        7: "eight of chalices, upright: walking away, disillusionment, leaving behind.",
        8: "nine of chalices, upright: satisfaction, emotional stability, luxury.",
        9: "ten of chalices, upright: inner happiness, fulfillment, dreams coming true.",
        10: "ace of chalices, upright:  new feelings, spirituality, intuition.",
        11: "king of chalices, upright: compassion, control, balance.",
        12: "knight of chalices, upright: following the heart, idealist, romantic.",
        13: "knave of chalices, upright: happy surprise, dreamer, sensitivity.",
        14: "queen of chalices, upright: compassion, calm, comfort.",
        15: "two of pentacles, upright: balancing decisions, priorities, adapting to change.",
        16: "three of pentacles, upright: teamwork, collaboration, building.",
        17: "four of pentacles, upright: conservation, frugality, security.",
        18: "five of pentacles, upright: need, poverty, insecurity.",
        19: "six of pentacles, upright: charity, generosity, sharing.",
        20: "seven of pentacles, upright: hard work, perseverance, diligence.",
        21: "eight of pentacles, upright: apprenticeship, passion, high standards.",
        22: "nine of pentacles, upright: fruits of labor, rewards, luxury.",
        23: "ten of pentacles, upright: legacy, culmination, inheritance.",
        24: "ace of pentacles, upright: opportunity, prosperity, new venture.",
        25: "king of pentacles, upright: abundance, prosperity, security.",
        26: "knave of pentacles, upright: ambition, desire, diligence.",
        27: "knight of pentacles, upright: efficiency, hard work, responsibility.",
        28: "queen of pentacles, upright: practicality, creature comforts, financial security.",
        29: "two of swords, upright: difficult choices, indecision, stalemate.",
        30: "three of swords, upright: heartbreak, suffering, grief.",
        31: "four of swords, upright: rest, restoration, contemplation.",
        32: "five of swords, upright: unbridled ambition, win at all costs, sneakiness.",
        33: "six of swords, upright: transition, leaving behind, moving on.",
        34: "seven of swords, upright: deception, trickery, tactics and strategy.",
        35: "eight of swords, upright: imprisonment, entrapment, self-victimization.",
        36: "nine of swords, upright: anxiety, hopelessness, trauma.",
        37: "ten of swords, upright: failure, collapse, defeat.",
        38: "ace of swords, upright: breakthrough, clarity, sharp mind.",
        39: "king of swords, upright: head over heart, discipline, truth.",
        40: "knave of swords, upright: curiosity, restlessness, mental energy.",
        41: "knight of swords, upright: action, impulsiveness, defending beliefs.",
        42: "queen of swords, upright: complexity, perceptiveness, clear mindedness.",
        43: "the chariot, upright: direction, control, willpower.",
        44: "death, upright: end of cycle, beginnings, change, metamorphosis.",
        45: "the devil, upright: addiction, materialism, playfulness.",
        46: "the emperor, upright: authority, structure, control, fatherhood.",
        47: "the empress, upright: motherhood, fertility, nature.",
        48: "the fool, upright: innocence, new beginnings, free spirit.",
        49: "the hanged man, upright: sacrifice, release, martyrdom.",
        50: "the hermit, upright: contemplation, search for truth, inner guidance.",
        51: "the hierophant, upright: tradition, conformity, morality, ethics.",
        52: "the high priestess, upright: intuitive, unconscious, inner voice.",
        53: "judgement, upright: reflection, reckoning, awakening.",
        54: "justice, upright: cause and effect, clarity, truth.",
        55: "the lovers, upright: partnerships, duality, union.",
        56: "the magician, upright: willpower, desire, creation, manifestation.",
        57: "the moon, upright: unconscious, illusions, intuition.",
        58: "the star, upright: hope, faith, rejuvenation.",
        59: "strength, upright: inner strength, bravery, compassion, focus.",
        60: "the sun, upright: joy, success, celebration, positivity.",
        61: "temperance, upright: middle path, patience, finding meaning.",
        62: "the tower, upright: sudden upheaval, broken pride, disaster.",
        63: "wheel of fortune, upright: change, cycles, inevitable fate.",
        64: "the world, upright: fulfillment, harmony, completion.",
        65: "two of wands, upright: planning, making decisions, leaving home.",
        66: "three of wands, upright: looking ahead, expansion, rapid growth.",
        67: "four of wands, upright: community, home, celebration.",
        68: "five of wands, upright: competition, rivalry, conflict.",
        69: "six of wands, upright: victory, success, public reward.",
        70: "seven of wands, upright: perseverance, defensive, maintaining control.",
        71: "eight of wands, upright: rapid action, movement, quick decisions.",
        72: "nine of wands, upright: resilience, grit, last stand.",
        73: "ten of wands, upright: accomplishment, responsibility, burden.",
        74: "ace of wands, upright: creation, willpower, inspiration, desire.",
        75: "king of wands, upright: big picture, leader, overcoming challenges.",
        76: "knave of wands, upright: exploration, excitement, freedom.",
        77: "knight of wands, upright: action, adventure, fearlessness.",
        78: "queen of wands, upright: courage, determination, joy.",
        79: "two of chalices, reversed: imbalance, broken communication, tension.",
        80: "three of chalices, reversed: overindulgence, gossip, isolation.",
        81: "queen of wands, reversed: selfishness, jealousy, insecurities.",
        82: "knight of wands, reversed: anger, impulsiveness, recklessness.",
        83: "knave of wands, reversed: lack of direction, procrastination, creating conflict.",
        84: "king of wands, reversed: impulsive, overbearing, unachievable expectations.",
        85: "ace of wands, reversed: lack of energy, lack of passion, boredom.",
        86: "ten of wands, reversed: inability to delegate, overstressed, burnt out.",
        87: "nine of wands, reversed: exhaustion, fatigue, questioning motivations.",
        88: "eight of wands, reversed: panic, waiting, slowdown.",
        89: "seven of wands, reversed: give up, destroyed confidence, overwhelmed.",
        90: "six of wands, reversed: excess pride, lack of recognition, punishment.",
        91: "five of wands, reversed: avoiding conflict, respecting differences.",
        92: "four of wands, reversed: lack of support, transience, home conflicts.",
        93: "three of wands, reversed: obstacles, delays, frustration.",
        94: "two of wands, reversed: fear of change, playing safe, bad planning.",
        95: "the world, reversed: incompletion, no closure.",
        96: "wheel of fortune, reversed: no control, clinging to control, bad luck.",
        97: "the tower, reversed: disaster avoided, delayed disaster, fear of suffering.",
        98: "temperance, reversed: extremes, excess, lack of balance.",
        99: "the sun, reversed: negativity, depression, sadness.",
        100: "strength, reversed: self doubt, weakness, insecurity.",
        101: "the star, reversed: faithlessness, discouragement, insecurity.",
        102: "the moon, reversed: confusion, fear, misinterpretation.",
        103: "the magician, reversed: trickery, illusions, out of touch.",
        104: "the lovers, reversed: loss of balance, one-sidedness, disharmony.",
        105: "justice, reversed: dishonesty, unaccountability, unfairness.",
        106: "judgement, reversed: lack of self awareness, doubt, self loathing.",
        107: "the high priestess, reversed: lack of center, lost inner voice, repressed feelings.",
        108: "the hierophant, reversed: rebellion, subversiveness, new approaches.",
        109: "the hermit, reversed: loneliness, isolation, lost your way.",
        110: "the hanged man, reversed: stalling, needless sacrifice, fear of sacrifice.",
        111: "the fool, reversed: recklessness, taken advantage of, inconsideration.",
        112: "the empress, reversed: dependence, smothering, emptiness, nosiness.",
        113: "the emperor, reversed: tyranny, rigidity, coldness.",
        114: "the devil, reversed: freedom, release, restoring control.",
        115: "death, reversed: fear of change, holding on, stagnation, decay.",
        116: "the chariot, reversed: lack of control, lack of direction, aggression.",
        117: "queen of swords, reversed: cold hearted, cruel, bitterness.",
        118: "knight of swords, reversed: no direction, disregard for consequences, unpredictability.",
        119: "knave of swords, reversed: deception, manipulation, all talk.",
        120: "king of swords, reversed: manipulative, cruel, weakness.",
        121: "ace of swords, reversed: confusion, brutality, chaos.",
        122: "ten of swords, reversed: can't get worse, only upwards, inevitable end.",
        123: "nine of swords, reversed: hope, reaching out, despair.",
        124: "eight of swords, reversed: self acceptance, new perspective, freedom.",
        125: "seven of swords, reversed: coming clean, rethinking approach, deception.",
        126: "six of swords, reversed: emotional baggage, unresolved issues, resisting transition.",
        127: "five of swords, reversed: lingering resentment, desire to reconcile, forgiveness.",
        128: "four of swords, reversed: restlessness, burnout, stress.",
        129: "three of swords, reversed: recovery, forgiveness, moving on.",
        130: "two of swords, reversed: lesser of two evils, no right choice, confusion.",
        131: "queen of pentacles, reversed: self-centeredness, jealousy, smothering.",
        132: "knight of pentacles, reversed: laziness, obsessiveness, work without reward.",
        133: "knave of pentacles, reversed: lack of commitment, greediness, laziness.",
        134: "king of pentacles, reversed: laziness, obsessiveness, work without reward.",
        135: "ace of pentacles, reversed: lost opportunity, missed chance, bad investment.",
        136: "ten of pentacles, reversed: fleeting success, lack of stability, lack of resources.",
        137: "four of chalices, reversed: sudden awareness, choosing happiness, acceptance.",
        138: "five of chalices, reversed: acceptance, moving on, finding peace.",
        139: "six of chalices, reversed: moving forward, leaving home, independence.",
        140: "seven of chalices, reversed: lack of purpose, diversion, confusion.",
        141: "eight of chalices, reversed: avoidance, fear of change, fear of loss.",
        142: "nine of chalices, reversed: lack of inner joy, smugness, dissatisfaction.",
        143: "ten of chalices, reversed: shattered dreams, broken family, domestic disharmony.",
        144: "ace of chalices, reversed: emotional loss, blocked creativity, emptiness.",
        145: "king of chalices, reversed: coldness, moodiness, bad advice.",
        146: "knight of chalices, reversed: moodiness, disappointment.",
        147: "knave of chalices, reversed: emotional immaturity, insecurity, disappointment.",
        148: "queen of chalices, reversed: martyrdom, insecurity, dependence.",
        149: "two of pentacles, reversed: loss of balance, disorganized, overwhelmed.",
        150: "nine of pentacles, reversed: reckless spending, living beyond means, false success.",
        151: "four of pentacles, reversed: greediness, stinginess, possessiveness.",
        152: "three of pentacles, reversed: lack of teamwork, disorganized, group conflict.",
        153: "six of pentacles, reversed: strings attached, stinginess, power and domination.",
        154: "five of pentacles, reversed: recovery, charity, improvement.",
        155: "seven of pentacles, reversed: work without results, distractions, lack of rewards.",
        156: "eight of pentacles, reversed: lack of passion, uninspired, no motivation."
        }
    for i in range(a):
        num = random.randrange(1, 157, 1)
        img = Image.open(str(num)+'.jpg')
        img.show()
        print switcher.get(num)
=======
from PIL import Image
import random
num = random.randrange(1, 79, 1)
img = Image.open(str(num)+'.jpg')
img.show()
>>>>>>> 5b9ac078c5134283d8efc676c0e95200a2d6fc95
